name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: macos-14
    steps:
      - name: Save Docker Images
        run: brew install docker --cask;systemctl start docker;docker pull gcr.io/distroless/static-debian11:nonroot;docker save gcr.io/distroless/static-debian11:nonroot -o images-pull-coredns-base-arm64.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: images-pull-coredns-base-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
