name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull debian:stable-slim;docker save debian:stable-slim -o images-pull-coredns-build-base-amd64.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: images-pull-coredns-build-base-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
