name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubicloud-standard-2-arm
    steps:
      - name: Save Docker Images
        run: docker pull registry.k8s.io/coredns/coredns:v1.11.1;docker save registry.k8s.io/coredns/coredns:v1.11.1 -o images-pull-coredns-amd64.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: images-pull-coredns-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
